// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5oPk5CKkqE2fEpjptJwuGpc53LUucDqI',
    appId: '1:1065041854808:web:1005ba1e795a8d1e0ee52d',
    messagingSenderId: '1065041854808',
    projectId: 'mk-project-brain-blocks',
    authDomain: 'mk-project-brain-blocks.firebaseapp.com',
    storageBucket: 'mk-project-brain-blocks.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqxlwlaN-9q4ZnDhEYNhZ6FpBrjL1hifQ',
    appId: '1:1065041854808:android:92f026125728a8a80ee52d',
    messagingSenderId: '1065041854808',
    projectId: 'mk-project-brain-blocks',
    storageBucket: 'mk-project-brain-blocks.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1iYq1W1tWiCcq5AKsKviLSjBG3bYSMk4',
    appId: '1:1065041854808:ios:95a3f88ce66268190ee52d',
    messagingSenderId: '1065041854808',
    projectId: 'mk-project-brain-blocks',
    storageBucket: 'mk-project-brain-blocks.firebasestorage.app',
    iosBundleId: 'com.mkproject.brain-blocks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1iYq1W1tWiCcq5AKsKviLSjBG3bYSMk4',
    appId: '1:1065041854808:ios:a46a8351f7e1d5fb0ee52d',
    messagingSenderId: '1065041854808',
    projectId: 'mk-project-brain-blocks',
    storageBucket: 'mk-project-brain-blocks.firebasestorage.app',
    iosBundleId: 'com.example.brainBlocks',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5oPk5CKkqE2fEpjptJwuGpc53LUucDqI',
    appId: '1:1065041854808:web:3c292b345cd773ad0ee52d',
    messagingSenderId: '1065041854808',
    projectId: 'mk-project-brain-blocks',
    authDomain: 'mk-project-brain-blocks.firebaseapp.com',
    storageBucket: 'mk-project-brain-blocks.firebasestorage.app',
  );
}
